name: Generate coverage
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  php-coverage:
    name: Create PHP coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: ffi
          coverage: xdebug
      - name: Install dependencies
        run: composer install
      - name: Generate coverage
        run: php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-cobertura=cobertura1.xml
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: cobertura1.xml
          name: cobertura-php
          retention-days: 1

  go-coverage:
    name: Create Go coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install libolm
        run: sudo apt-get update && sudo apt-get install -y libolm-dev
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: lib/go.mod
      - name: Install converter
        run: go install github.com/boumenot/gocover-cobertura@latest
      - name: Generate coverage
        run: |
          cd lib
          go test -coverprofile=coverage.txt -covermode count -v ./...
          gocover-cobertura < coverage.txt > ../cobertura2.xml
          rm -rf coverage.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: cobertura2.xml
          name: cobertura-go
          retention-days: 1

  merge-coverages:
    name: Merge coverages
    needs:
      - go-coverage
      - php-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Download coverages
        uses: actions/download-artifact@v5
      - name: Install merger
        run: npm -g install cobertura-merge
      - name: Merge coverages
        run: cobertura-merge -o cobertura.xml php=cobertura-php/cobertura1.xml go=cobertura-go/cobertura2.xml
      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          format: markdown
          badge: true
          hide_complexity: true
          output: file
      - name: Comment coverage summary on PR
        if: github.event_name == 'pull_request' && hashFiles('coverage.xml') != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
