name: Compile Golang bridge
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            job: build-linux-x64
            name: x86_64
            filePart: x86
          - os: ubuntu-24.04-arm
            job: build-linux-aarch64
            name: arm64
            filePart: arm
    name: Compile (x86_64)
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install libolm
        run: sudo apt-get update && sudo apt-get -y install libolm-dev
      - name: Build
        run: |
          cd lib
          make ${{ matrix.job }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: lib/out/libmatrix.linux.${{ matrix.filePart }}.64.so
          retention-days: 1
#  compile_x86_64:
#    name: Compile (x86_64)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Install libolm
#        run: sudo apt-get update && sudo apt-get -y install libolm-dev
#      - name: Build
#        run: |
#          cd lib
#          make build-linux-x64
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: 'x86_64'
#          path: lib/out/libmatrix.linux.x86.64.so
#          retention-days: 1
#  compile_arm64:
#    name: Compile (arm64)
#    runs-on: ubuntu-24.04-arm
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Install libolm
#        run: sudo apt-get update && sudo apt-get -y install libolm-dev
#      - name: Build
#        run: |
#          cd lib
#          make build-linux-aarch64
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: 'arm64'
#          path: lib/out/libmatrix.linux.arm.64.so
#          retention-days: 1
