name: Compile Golang bridge
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  compile_x86_64:
    name: Compile (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install libolm
        run: apt-get update && apt-get -y install libolm-dev
      - name: Build
        run: |
          cd lib
          make build-linux-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: lib/out/libmatrix.linux.x86.64.so
          retention-days: 1
