name: Test PHP library

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: ffi
          coverage: none
      - name: Validate composer.json
        run: composer validate --no-interaction --no-check-publish
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Run PHPUnit
        run: vendor/bin/phpunit
