name: Test Golang bridge

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  go-tests:
    name: Run Golang tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install libolm
        run: sudo apt-get update && sudo apt-get install -y libolm-dev
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: lib/go.mod
      - name: Run tests
        working-directory: lib
        run: go test -tags goolm ./...
