name: Test Golang bridge

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      golang: ${{ steps.filter.outputs.golang }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            golang:
              - 'lib/**'

  go-tests:
    name: Run Golang tests
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.golang == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install libolm
        run: sudo apt-get update && sudo apt-get install -y libolm-dev
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: lib/go.mod
      - name: Run tests
        working-directory: lib
        run: go test -tags goolm ./...
